using System.Globalization;
using System.Text;

namespace IcomRigControl.Services;

/// <summary>
/// Writes QsoRecord data as standard ADIF (Amateur Data Interchange Format)
/// text, importable by any logging program (N1MM, Log4OM, DXKeeper, etc.).
/// ADIF fields use the &lt;FIELDNAME:length&gt;value tagging convention.
/// </summary>
public static class AdifWriter
{
    private const string ProgramId = "IcomRigControl";
    private const string ProgramVersion = "1.0";
    private const string AdifVersion = "3.1.4";

    public static string GenerateHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("Generated by IcomRigControl");
        sb.Append(Field("ADIF_VER", AdifVersion));
        sb.Append(Field("PROGRAMID", ProgramId));
        sb.Append(Field("PROGRAMVERSION", ProgramVersion));
        sb.AppendLine("<EOH>");
        return sb.ToString();
    }

    public static string FormatQso(QsoRecord qso)
    {
        var sb = new StringBuilder();

        sb.Append(Field("CALL", qso.Callsign));
        sb.Append(Field("BAND", qso.Band));
        sb.Append(Field("MODE", qso.Mode));
        sb.Append(Field("QSO_DATE", qso.DateTimeUtc.ToString("yyyyMMdd", CultureInfo.InvariantCulture)));
        sb.Append(Field("TIME_ON", qso.DateTimeUtc.ToString("HHmm", CultureInfo.InvariantCulture)));
        sb.Append(Field("FREQ", qso.FrequencyMHz.ToString("0.######", CultureInfo.InvariantCulture)));
        sb.Append(Field("RST_SENT", qso.RstSent));
        sb.Append(Field("RST_RCVD", qso.RstReceived));

        if (!string.IsNullOrEmpty(qso.Name))
            sb.Append(Field("NAME", qso.Name));
        if (!string.IsNullOrEmpty(qso.GridSquare))
            sb.Append(Field("GRIDSQUARE", qso.GridSquare));
        if (!string.IsNullOrEmpty(qso.Notes))
            sb.Append(Field("NOTES", qso.Notes));
        if (!string.IsNullOrEmpty(qso.ContestExchangeSent))
            sb.Append(Field("STX_STRING", qso.ContestExchangeSent));
        if (!string.IsNullOrEmpty(qso.ContestExchangeReceived))
            sb.Append(Field("SRX_STRING", qso.ContestExchangeReceived));
        if (qso.SerialNumberSent.HasValue)
            sb.Append(Field("STX", qso.SerialNumberSent.Value.ToString(CultureInfo.InvariantCulture)));
        if (qso.SerialNumberReceived.HasValue)
            sb.Append(Field("SRX", qso.SerialNumberReceived.Value.ToString(CultureInfo.InvariantCulture)));

        sb.Append("<EOR>");
        return sb.ToString();
    }

    public static void WriteToFile(string path, IEnumerable<QsoRecord> qsos)
    {
        var sb = new StringBuilder();
        sb.Append(GenerateHeader());
        foreach (var qso in qsos)
        {
            sb.AppendLine();
            sb.AppendLine(FormatQso(qso));
        }
        File.WriteAllText(path, sb.ToString());
    }

    private static string Field(string name, string value) =>
        $"<{name}:{value.Length}>{value}";
}